# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Affinitas' do
pod 'AFNetworking', '~> 2.0'
pod 'JSONModel', '~> 1.1'
pod 'ISO8601', '~> 0.3'
pod 'ActionSheetPicker-3.0', '~> 2.0.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'DKHelper', '~> 0.9.5'
pod 'MagicalRecord'
pod 'SDWebImage', '~>3.7'
end

